SFU_Link/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/contact', to: 'pages#contact'
  get 'pages/profile', to: 'pages#profile'
  get 'pages/match', to: 'pages#match'


  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  post 'signup', to: 'sessions#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


end

SFU_Link/app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[sfu]+\.[ca]+\z/i
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
  validates :password, :confirmation => true
  validates_confirmation_of :password
  has_secure_password
end

SFU_Link/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

SFU_Link/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def signup
  end

  def profile
  end

  def match
    @users = User.all
    @colors = ["purple", "blue", "indigo", "cyan", "lime", "brown"]
    @possible_partners = []
    @users.each do |user|
      if user.gender != current_user.gender
        @possible_partners.push(user)
      end
    end
  end
end

SFU_Link/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end


  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in #{user.firstname}"
      redirect_to pages_profile_path
    else
      flash.now[:danger] = "Invalid login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

SFU_Link/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to SFU Link #{@user.firstname}"

      redirect_to login_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your profile was updated successfully"
      redirect_to pages_profile_path
    else
      render 'edit'
    end
  end

private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :gender, :description, :faculty)
  end
end

SFU_Link/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">


  <%= link_to image_tag("logo/SFU_logo.png", width:"60", height: "40", class: "d-inline-block align-top navbar-brand", alt: ""), root_path %>
  <%= link_to "SFU Link", root_path, class:"navbar-brand"%>

  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to "About", pages_about_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to "Contact Us", pages_contact_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link"%>

          </li>
      <li class="navbar fixed-bottom navbar-dark bg-dark">


      <a class="navbar-brand" href="#"a>
        <%= link_to "Profile", pages_profile_path, class: "nav-link"%>


      <a class="navbar-brand" href="#"a>
      <%= link_to "Contact Us", pages_contact_path, class: "nav-link"%>


      <a class="navbar-brand" href="#"a>
      <%= link_to "Match", pages_match_path, class: "nav-link"%>
    </li>


      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Get Started
          </a>
          <div class="dropdown-menu text_left">
            <%= link_to "Log in", login_path, class: "dropdown-item"%>
            <%= link_to "Sign up", signup_path, class: "dropdown-item"%>
          </div>
        </li>
      <% end %>
  </ul>
</nav>

SFU_Link/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SFULink</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap.min.js'%>
    
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

SFU_Link/app/views/pages/about.html.erb
<!-- Header -->
<header class="bg-danger text-center py-5 mb-4">
  <div class="container">
    <h1 class="font-weight-light text-white">Our Mission</h1>
  </div>
</header>

<br></br>

<body>

  <p>
    <p style="font-size:22px; font-family:arial;">
      &emsp;
      The purpose of SFU Link is to help SFU students find a significant other, or even just a friend through means of online communication.
      We strive to make being single more fun and rewarding by connecting students who may not have otherwise met in real life. We celebrate that being single is a journey. And a great one.
      </font>
  </p>
</body>

<br style = "line-height:6;">

<!-- Header -->
<header class="bg-warning text-center py-5 mb-4">
  <div class="container">
    <h1 class="font-weight-light text-white">Meet the Team</h1>
  </div>
</header>


<!-- Team members -->
<div class="container">
  <div class="row">
    <!-- Team Member 1 -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img style= "width: 250px; height: 250px;" src="https://media.licdn.com/dms/image/C5603AQE0RXZ3bbb8Tg/profile-displayphoto-shrink_200_200/0?e=1567641600&v=beta&t=o2zELgoxYlSHdzugCgt-cD73J_gdiJhvqEv-peWTj0I" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Rajan Grewal</h5>
            <div class="card-text text-black-50">Team Leader</div>
          </div>
        </div>
    </div>
    <!-- Team Member 2 -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img style= "width: 250px; height: 250px;" src="https://voteformost.net/wp-content/uploads/fv-contest/c55/image.jpeg" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Kevin Km Lee</h5>
            <div class="card-text text-black-50">Technical Lead</div>
          </div>
        </div>
    </div>
    <!-- Team Member 3 -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img style= "width: 250px; height: 250px;" src="https://scontent.fcxh2-1.fna.fbcdn.net/v/t1.0-1/p160x160/36188900_1819169251499670_2247203051922259968_n.jpg?_nc_cat=107&_nc_oc=AQlrUs52DYd4C7Hwib5DnP4IoD5S4lRISBb0I2eC7kuU-XNSvECvhNVP2if8-m99vUA&_nc_ht=scontent.fcxh2-1.fna&oh=00e0b3731d21761b294ed5f10a4546bb&oe=5DC34AD5" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Adrian Wong</h5>
            <div class="card-text text-black-50">Web Developer</div>
          </div>
        </div>
    </div>
    <!-- Team Member 4 -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img style= "width: 250px; height: 250px;" src="https://scontent.fcxh2-1.fna.fbcdn.net/v/t1.0-1/c107.31.391.391a/s160x160/421715_525336010825357_529087902_n.jpg?_nc_cat=110&_nc_oc=AQk0paCHjBW5HRbLpbp3DNKCW9Gg0Y2a2AUs6Nu3K5Q1gXPtTpx3OMyFYDQ84pfkeLs&_nc_ht=scontent.fcxh2-1.fna&oh=85af205044baf2b1400ca1e5fd0d04a7&oe=5DB01874" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Joshua Clark</h5>
            <div class="card-text text-black-50">Web Developer</div>
          </div>
        </div>
    </div>
  </div>
  <!-- Team Member 5 -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-0 shadow">
      <img style= "width: 250px; height: 250px;" src="https://scontent.fyvr3-1.fna.fbcdn.net/v/t1.0-9/18519831_914096912063280_2572492200936052020_n.jpg?_nc_cat=107&_nc_oc=AQnSaRkc5MO_Y1h2X_v8x2cUZp5W7GoxtC6k_UJ5NEfcBDi3v74qMQs7vitMQDyhEG0&_nc_ht=scontent.fyvr3-1.fna&oh=d28b5f3396899ef105347aaf8368ba64&oe=5DC36092" class="card-img-top" alt="...">
        <div class="card-body text-center">
          <h5 class="card-title mb-0">Peter Lan</h5>
          <div class="card-text text-black-50">Web Developer</div>
        </div>
      </div>
  </div>
</div>
  <!-- /.row -->




<!-- FOOTER -->
<footer class="container">
  <p class="float-right">
    <a href="#">Back to top</a>
  </p>
  <p>
    &copy; 2019 SFU Link Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
  </p>
</footer>

</div>
<!-- /.container -->

SFU_Link/app/views/pages/contact.html.erb
<header>
	<h1>Contact us</h1>
</header>

<div id="form">

<div class="fish" id="fish"></div>
<div class="fish" id="fish2"></div>

<form id="waterform" method="post">

<div class="formgroup" id="name-form">
    <label for="name">Your name*</label>
    <input type="text" id="name" name="name" />
</div>

<div class="formgroup" id="email-form">
    <label for="email">Your e-mail*</label>
    <input type="email" id="email" name="email" />
</div>

<div class="formgroup" id="message-form">
    <label for="message">Your message</label>
    <textarea id="message" name="message"></textarea>
</div>

	<input type="submit" value="Send your message!" />
</form>
</div>

<!-- FOOTER -->
<footer class="container">
  <p class="float-right">
    <a href="#">Back to top</a>
  </p>
  <p>
    &copy; 2019 SFU Link Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
  </p>
</footer>


  
 
<style >
@import url(https://fonts.googleapis.com/css?family=Sniglet|Raleway:900);


body, html {
    height: 100%;
    padding: 0;
    margin: 0;
    font-family: 'Sniglet', cursive;
}

h1 {
    font-weight: normal;
    font-size: 4em;
    font-family: 'Raleway', sans-serif;
    margin: 0 auto;
    margin-top: 30px;
    width: 500px;
    color: #F90;
    text-align: center;
}

/* Animation webkit */
@-webkit-keyframes myfirst {
    0% {
        margin-left: -235px
    }

    90% {
        margin-left: 100%;
    }

    100% {
        margin-left: 100%;
    }
}

/* Animation */
@keyframes myfirst {
    0% {
        margin-left: -235px
    }

    70% {
        margin-left: 100%;
    }

    100% {
        margin-left: 100%;
    }
}

.fish {
    background-image: url('http://www.geertjanhendriks.nl/codepen/form/fish.png');
    width: 235px;
    height: 104px;
    margin-left: -235px;
    position: absolute;
    animation: myfirst 24s;
    -webkit-animation: myfirst 24s;
    animation-iteration-count: infinite;
    -webkit-animation-iteration-count: infinite;
    animation-timing-function: linear;
    -webkit-animation-timing-function: linear;
}

#fish {
    top: 120px;
}

#fish2 {
    top: 260px;
    animation-delay: 12s;
    -webkit-animation-delay: 12s;
}


header {
    height: 160px;
    background: url('http://www.geertjanhendriks.nl/codepen/form/golf.png') repeat-x bottom;
}

#form {
    height: 100%;
    background-color: #98d4f3;
    overflow: hidden;
    position: relative;
}

form {
    margin: 0 auto;
    width: 500px;
    padding-top: 40px;
    color: white;
    position: relative;
}

label, input, textarea {
    display: block;
}

input, textarea {
    width: 500px;
    border: none;
    border-radius: 20px;
    outline: none;
    padding: 10px;
    font-family: 'Sniglet', cursive;
    font-size: 1em;
    color: #676767;
    transition: border 0.5s;
    -webkit-transition: border 0.5s;
    -moz-transition: border 0.5s;
    -o-transition: border 0.5s;
    border: solid 3px #98d4f3;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

    input:focus, textarea:focus {
        border: solid 3px #77bde0;
    }

textarea {
    height: 100px;
    resize: none;
    overflow: auto;
}

input[type="submit"] {
    background-color: #F90;
    color: white;
    height: 50px;
    cursor: pointer;
    margin-top: 30px;
    font-size: 1.29em;
    font-family: 'Sniglet', cursive;
    -webkit-transition: background-color 0.5s;
    -moz-transition: background-color 0.5s;
    -o-transition: background-color 0.5s;
    transition: background-color 0.5s;
}

    input[type="submit"]:hover {
        background-color: #e58f0e;
    }

label {
    font-size: 1.5em;
    margin-top: 20px;
    padding-left: 20px;
}

.formgroup, .formgroup-active, .formgroup-error {
    background-repeat: no-repeat;
    background-position: right bottom;
    background-size: 10.5%;
    transition: background-image 0.7s;
    -webkit-transition: background-image 0.7s;
    -moz-transition: background-image 0.7s;
    -o-transition: background-image 0.7s;
    width: 566px;
    padding-top: 2px;
}

.formgroup {
    background-image: url('http://www.geertjanhendriks.nl/codepen/form/pixel.gif');
}

.formgroup-active {
    background-image: url('http://www.geertjanhendriks.nl/codepen/form/octo.png');
}

.formgroup-error {
    background-image: url('http://www.geertjanhendriks.nl/codepen/form/octo-error.png');
    color: red;
}
</style >



  
  
<script>
$('document').ready(function(){
	$('input[type="text"], input[type="email"], textarea').focus(function(){
		var background = $(this).attr('id');
		$('#' + background + '-form').addClass('formgroup-active');
		$('#' + background + '-form').removeClass('formgroup-error');
	});
	$('input[type="text"], input[type="email"], textarea').blur(function(){
		var background = $(this).attr('id');
		$('#' + background + '-form').removeClass('formgroup-active');
	});

function errorfield(field){
	$(field).addClass('formgroup-error');
	console.log(field);	
}

$("#waterform").submit(function() {
	var stopsubmit = false;

if($('#name').val() == "") {
	errorfield('#name-form');
	stopsubmit=true;
}
if($('#email').val() == "") {
	errorfield('#email-form');
	stopsubmit=true;
}
  if(stopsubmit) return false;
});
		
});
</script>

SFU_Link/app/views/pages/home.html.erb
<body>
  <main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" style="height: auto; object-fit: cover;">
        <div class="carousel-item active">
          <%= image_tag("logo/SFU_campus_1.jpg", class: "first-slide d-block w-100 .img-fluid", alt: "First slide") %>
          <div class="container">
            <div class="carousel-caption text-left">
              <h1>SFU Link</h1>
              <p>Make Every Single Moment Count.</p>
              <%#p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p%>
              <%= link_to '<button type="button">Sign Up Today</button>'.html_safe, signup_path %>
              <%= link_to '<button type="button">Log In</button>'.html_safe, login_path %>

            </div>
          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag("logo/SFU_campus_2.jpg", class: "second-slide d-block w-100", alt: "Second slide") %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Love, Connect & Inspire with SFU Link.</h1>
              <p>We are here to help you to find your match with same interest or hobbies, lifestyle, and to help you find your dream love.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag("logo/students.jpg", class: "third-slide d-block w-100", alt: "Third slide") %>
          <div class="container">
            <div class="carousel-caption text-right">
              <h1>Get to know interesting people around you</h1>
              <p>Swipe right to like, and swipe left to forget. SFU Link is a fun and easy way to connect you with the people you like.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
      <br/>
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="rounded-circle" src="http://ontarioheartcenter.ca/wp-content/uploads/2017/04/img-2.png" width="140" height="140">
          <h2>A Magic Moment</h2>
            <p> When someone you liked likes you back, it’s a match! You only get notifications when you’re matched with someone. Say goodbye to the embarrassment!</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="https://cdn.thisiswhyimbroke.com/images/our-love-story-book.jpg" width="140" height="140">
          <h2>Your Game, Your Way</h2>
          <p>Chat only with the people you are matched with. You will never receive messages from random people.</p>
          <br>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="https://i.dailymail.co.uk/i/pix/2013/02/18/article-0-17AA20FB000005DC-859_638x462.jpg" width="140" height="140">
          <h2>Keep it to yourself</h2>
          <p>Your dating life is private. We get it. You can choose to hide your contacts, which will ensure contacts in your address book won’t be suggested to you, nor you to them.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">SFU Link is free for all users. <span class="text-muted">Why?</span></h2>
          <p class="lead">Because love is not to be purchased, and affection has no price.</p>
          <br>
          <p class="lead">If you’re here to meet new people from SFU, expand your social network, or just live in the now, you’ve come to the right place! </p>
        </div>
        <div class="col-md-5">
          <img style= "width: 400px; height: 200px;" src="https://www.jeevansathi.com/blog/wp-content/uploads/2018/07/couple-understandings.jpg">
        </div>
      </div>

       <hr class="featurette-divider">

       <div class="row featurette">
        <div class="col-md-7 order-md-2">
          <h2 class="featurette-heading">Not sure who's your type? </span></h2>
          <p class="lead">
            Don't worry, we are here to help!
            <br></br>
            Based on your faculty, interests, and age preference, we will recommend you an outstanding individual.
          </p>
        </div>
        <div class="col-md-5 order-md-1">
          <img style= "width: 320px; height: 180px;" src="http://saltandlighttv.org/blog/wp-content/uploads/2015/10/LoveQuestion.jpg">
        </div>
       </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">
            Not just a dating app. </span>
          </h2>
          <p class="lead">
            <br>
            SFU Link make being single more fun and rewarding by connecting students who may not have otherwise met in real life. We celebrate that being single is a journey. And a great one.
          </p>
        </div>
      <div class="col-md-5">
        <img style= "width: 400px; height: 200px;" src="https://fcda83403961100baa63-6b75d3a70c699e63772caac69eefc7e8.ssl.cf5.rackcdn.com/cdn_27Da0NkqYhy67l2ahjRWJzuU64K-SJhg.jpg">
      </div>
     </div>

     <hr class="featurette-divider">

     <!-- /END THE FEATURETTES -->


    </div><!-- /.container -->


    <!-- FOOTER -->
    <footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; 2019 SFU Link Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
  </main>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
  <script src="../../../../assets/js/vendor/popper.min.js"></script>
  <script src="../../../../dist/js/bootstrap.min.js"></script>
  <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
  <script src="../../../../assets/js/vendor/holder.min.js"></script>
</body>

SFU_Link/app/views/pages/login.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign In</h5>
            <form class="form-signin">
              <div class="form-label-group">
                <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                <label for="inputEmail">SFU Email address</label>
              </div>

              <div class="form-label-group">
                <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                <label for="inputPassword">Password</label>
              </div>

              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Remember password</label>
              </div>
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

SFU_Link/app/views/pages/match.html.erb
<%= javascript_tag do %>
$(document).ready(function() {

  var animating = false;
  var cardsCounter = 0;
  var numOfCards = <%= @possible_partners.length %>;
  var decisionVal = 80;
  var pullDeltaX = 0;
  var deg = 0;
  var $card, $cardReject, $cardLike

  function pullChange() {
    animating = true;
    deg = pullDeltaX / 10;
    $card.css("transform", "translateX("+ pullDeltaX +"px) rotate("+ deg +"deg)");

    var opacity = pullDeltaX / 100;
    var rejectOpacity = (opacity >= 0) ? 0 : Math.abs(opacity);
    var likeOpacity = (opacity <= 0) ? 0 : opacity;
    $cardReject.css("opacity", rejectOpacity);
    $cardLike.css("opacity", likeOpacity);
  };

  function check_match(current_name, selected_name){
    localStorage.setItem(current_name, selected_name);

    if (selected_name in localStorage){
      alert("Matched\nNow put this information in the Matching table");
    };
  };

  function release() {
    localStorage.clear()
    if (pullDeltaX >= decisionVal) {
      $card.addClass("to-right");
      var selected_name = $card.find("p:first").text();
      var name_list = document.getElementsByClassName("demo__card__name");
      var current_name = "<%= current_user.firstname.html_safe + " " + current_user.lastname.html_safe %>";

      check_match(current_name, selected_name);

    } else if (pullDeltaX <= -decisionVal) {
      $card.addClass("to-left");
    }

    if (Math.abs(pullDeltaX) >= decisionVal) {
      $card.addClass("inactive");

      setTimeout(function() {
        $card.addClass("below").removeClass("inactive to-left to-right");
        cardsCounter++;
        if (cardsCounter === numOfCards) {
          cardsCounter = 0;
          $(".demo__card").removeClass("below");
        }
      }, 300);
    }

    if (Math.abs(pullDeltaX) < decisionVal) {
      $card.addClass("reset");
    }

    setTimeout(function() {
      $card.attr("style", "").removeClass("reset")
        .find(".demo__card__choice").attr("style", "");

      pullDeltaX = 0;
      animating = false;
    }, 300);
  };

  $(document).on("mousedown touchstart", ".demo__card:not(.inactive)", function(e) {
    if (animating) return;

    $card = $(this);
    $cardReject = $(".demo__card__choice.m--reject", $card);
    $cardLike = $(".demo__card__choice.m--like", $card);
    var startX =  e.pageX || e.originalEvent.touches[0].pageX;

    $(document).on("mousemove touchmove", function(e) {
      var x = e.pageX || e.originalEvent.touches[0].pageX;
      pullDeltaX = (x - startX);
      if (!pullDeltaX) return;
      pullChange();
    });

    $(document).on("mouseup touchend", function() {
      $(document).off("mousemove touchmove mouseup touchend");
      if (!pullDeltaX) return; // prevents from rapid click events
      release();
    });
  });
});
<% end %>
<div class="demo">
  <header class="demo__header">Matching</header>
  <div class="demo__content">
    <div class="demo__card-cont">
      <% @possible_partners.each do |candidate| %>
        <div class="demo__card">
          <div class="demo__card__top <%= @colors.shuffle.first %>">
            <div class="demo__card__img"></div>
            <p class="demo__card__name"><%= candidate.firstname %> <%= candidate.lastname %></p>
          </div>
          <div class="demo__card__btm">
            <p class="demo__card__we"><%=candidate.description%></p>
          </div>
          <div class="demo__card__choice m--reject"></div>
          <div class="demo__card__choice m--like"></div>
          <div class="demo__card__drag"></div>
        </div>
      <% end %>
    </div>
    <p class="demo__tip">Swipe left or right</p>
  </div>
</div>